### ISSUE TITLE
clipto causing laptop to freeze and crash 

### ISSUE THREAD

**Issue by roamerhappiness** [clipto-pro/Desktop#17]
I have two laptops both with Clipto Pro installed. Clipto has worked great on both laptops for some time now but recently I installed version 1.3.0 on both laptops and now Clipto is causing one laptop to move very slow, freeze, and crash repeatedly. At first I did not have any reason to think it was Clipto causing the problem. I cleared the cache and cookies from the browsers, preformed a Windows disk cleanup, disabled all the startup applications, and defragmented the hard drive. After disabling all startup applications and restarting the laptop, it began to function normally again. After defragmenting and restarting again, the first program I turned on was Clipto, and I could tell immediately the computer was slowing again and Clipto took a very long time to open and the laptop was so slow I could not do anything until Clipto opened. I closed Clipto and restarted again and the laptop began working normally again. I re-enabled all the startup applications but I left Clipto off and the laptop is working fine so the problem seems to only happen with Clipto active. My other laptop has Clipto active and is still working fine so it's only a problem on the one laptop. The laptop having the issue is an Asus Laptop model Q302L-BBI5T14 with Windows 10 Home,

**Comment by atrashler** [comment]
Will check it. If the previous version worked fine please downgrade to it while we are trying to reproduce the issue and solve it.

**Comment by atrashler** [comment]
> I have two laptops both with Clipto Pro installed. Clipto has worked great on both laptops for some time now but recently I installed version 1.3.0 on both laptops and now Clipto is causing one laptop to move very slow, freeze, and crash repeatedly. At first I did not have any reason to think it was Clipto causing the problem. I cleared the cache and cookies from the browsers, preformed a Windows disk cleanup, disabled all the startup applications, and defragmented the hard drive. After disabling all startup applications and restarting the laptop, it began to function normally again. After defragmenting and restarting again, the first program I turned on was Clipto, and I could tell immediately the computer was slowing again and Clipto took a very long time to open and the laptop was so slow I could not do anything until Clipto opened. I closed Clipto and restarted again and the laptop began working normally again. I re-enabled all the startup applications but I left Clipto off and the laptop is working fine so the problem seems to only happen with Clipto active. My other laptop has Clipto active and is still working fine so it's only a problem on the one laptop. The laptop having the issue is an Asus Laptop model Q302L-BBI5T14 with Windows 10 Home,

Question: when it happened did you use 'Track Clipboard' functionality or not?

**Comment by atrashler** [comment]
@roamerhappiness,

We have published a new build (https://github.com/clipto-pro/Desktop/releases/download/v1.3.2/clipto.pro-1.3.2.exe).
Could you please download it and check the problem in two different scenarios:
1) when 'Track Clipboard' is activated
2) when 'Track Clipboard' is not activated

Thanks!

**Comment by roamerhappiness** [comment]
I installed the new version but I am unable to get any of the settings to display.
![Capture](https://user-images.githubusercontent.com/55665696/65799674-b7d82e00-e142-11e9-9bc6-1c14b5b014f7.PNG)

**Comment by atrashler** [comment]
Yes. Sorry, broken build. Will update it soon..

**Comment by atrashler** [comment]
@roamerhappiness try this one - https://github.com/clipto-pro/Desktop/releases/download/v1.4.0/clipto.pro-1.4.0.exe

At least it works on one laptop:)

**Comment by roamerhappiness** [comment]
No need for apology. I am very grateful that you guys built this and are working on it. I feel bad for asking so much from you.

I installed 1.4 and it's still the same. The settings open a blank white applet. I also tried the sign in link and it also shows a blank white applet.

I still have 1.3 on my other laptop which is still working fine. That laptop also has Windows 10 Home. Seems very odd to me that it would work on one and not the other. Is it possible there is something on my laptop that is causing this? I am not sure what it could be since it happens even with everything else shut off, although stuff can run in the background without my knowledge I guess.

Is there anyway I can get some logs or details from my system to maybe give you guys a better shot at guessing what is wrong? I am willing to get on a call and share my screen or my desktop controls with you.

**Comment by roamerhappiness** [comment]
Okay so this is very strange. I just decided to install 1.2 since you suggested earlier in this thread that I go back to a previous version. Now that version is having the same problems. That was not happening before when I first installed Clipto. I thought I used version 1.2 originally and it worked great. I have not installed any new programs in a long time so maybe this is due to a recent update from Windows or Chrome? I started to question which version of Clipto I actually started with. I tried all the previous versions and they have similar issues.

**Comment by roamerhappiness** [comment]
I decided to reformat my laptop. I reinstalled version 1.3 . It works fine now. I didn't have issues with anything else on the laptop except for your program but I like it so much it was worth it to just start over. I have no clue what could have caused all this. I am very sorry for hassling you. :(

**Comment by atrashler** [comment]
When the problem exists and someone is ready to cooperate to solve it - it is very very good:)
The empty settings screen seems like a visual issue and we will try to solve it.
If you have any problem with freeze or crash or any other strange behaviour while using the app please try to install the latest version 1.4.0 and check two scenarios that I have mentioned before. Even if it does not draw settings screen it should let to switch option “Track Clipboard” from system tray.

If it is not reproducable anymore it is also ok. Contact us when it will be. We will not cancel this issue.

**Comment by roamerhappiness** [comment]
I installed version 1.4 and everything works great.

**Comment by atrashler** [comment]
Have closed it due to passed performance tests (by our QA).
@roamerhappiness please keep in mind that the version 1.4.0 that you have installed is not officially released and can be incompatible with our next incremental update. Nothing dangerous but the next update can reset settings and authorisation. We are still thinking how to separate public and beta releases in the way as it done in Google Play...

**Comment by roamerhappiness** [comment]
After I reformatted, version 1.3 and version 1.4.1
